### ISSUE TITLE
[DOCUMENTATION] Проверить на соответсвие стандарту LSB

### ISSUE THREAD

**Issue by Drsheppard01** [CalmiraLinux/CalmiraLinux#68]
"Идеология
Дистрибутив старается следовать стандартам FHS и LSB в первую очередь. Помимо этого, дистрибутив "проповедует" KISS. В Calmira всё решает пользователь. Как ставить, куда ставить и что ставить. Как пользоваться дистрибутивом. Так же вы можете без каких-либо проблем делать сборки на основе Calmira - для этого предоставляется кросс-компилятор и временный инструментарий (https://github.com/Linuxoid85/CalmiraLinux/releases)."

Проверить на соответствие стандарту LSB 3.1 Глава 22. Полная ссылка: http://refspecs.linux-foundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/swinstall.html#SWINSTALL-INTRO

**Comment by Linuxoid85** [comment]
Планируется большое обновление документации. В новых релизах совместимость с LSB неполная. Например, другой формат пакетов и управление пакетами. Вместо них система портов.
